name: tdt4265
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - torch
      - ultralytics
      - torchvision
      - opencv-python
      - PyYAML
      - tqdm
      - matplotlib
      - numpy
      - pandas